/* tslint:disable */
/* eslint-disable */
/**
 * MedicalManagement.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ApiResult } from '../models';
import { DoctorAdviceInfoCreateDto } from '../models';
import { DoctorAdviceInfoDtoApiResult } from '../models';
import { DoctorAdviceInfoDtoPagedListDtoApiResult } from '../models';
import { DoctorAdviceInfoUpdateDto } from '../models';
import { GetPagedListDto } from '../models';
/**
 * DoctorAdviceInfoApi - axios parameter creator
 * @export
 */
export const DoctorAdviceInfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDoctorAdviceInfoDeleteIdDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiDoctorAdviceInfoDeleteIdDelete.');
            }
            const localVarPath = `/api/DoctorAdviceInfo/Delete/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDoctorAdviceInfoGetIdGet: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiDoctorAdviceInfoGetIdGet.');
            }
            const localVarPath = `/api/DoctorAdviceInfo/Get/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {GetPagedListDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDoctorAdviceInfoGetPagedListPost: async (body?: GetPagedListDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/DoctorAdviceInfo/GetPagedList`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DoctorAdviceInfoCreateDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDoctorAdviceInfoInsertPost: async (body?: DoctorAdviceInfoCreateDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/DoctorAdviceInfo/Insert`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {DoctorAdviceInfoUpdateDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDoctorAdviceInfoUpdatePut: async (body?: DoctorAdviceInfoUpdateDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/DoctorAdviceInfo/Update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DoctorAdviceInfoApi - functional programming interface
 * @export
 */
export const DoctorAdviceInfoApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDoctorAdviceInfoDeleteIdDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ApiResult>>> {
            const localVarAxiosArgs = await DoctorAdviceInfoApiAxiosParamCreator(configuration).apiDoctorAdviceInfoDeleteIdDelete(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDoctorAdviceInfoGetIdGet(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DoctorAdviceInfoDtoApiResult>>> {
            const localVarAxiosArgs = await DoctorAdviceInfoApiAxiosParamCreator(configuration).apiDoctorAdviceInfoGetIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {GetPagedListDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDoctorAdviceInfoGetPagedListPost(body?: GetPagedListDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DoctorAdviceInfoDtoPagedListDtoApiResult>>> {
            const localVarAxiosArgs = await DoctorAdviceInfoApiAxiosParamCreator(configuration).apiDoctorAdviceInfoGetPagedListPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {DoctorAdviceInfoCreateDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDoctorAdviceInfoInsertPost(body?: DoctorAdviceInfoCreateDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ApiResult>>> {
            const localVarAxiosArgs = await DoctorAdviceInfoApiAxiosParamCreator(configuration).apiDoctorAdviceInfoInsertPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {DoctorAdviceInfoUpdateDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDoctorAdviceInfoUpdatePut(body?: DoctorAdviceInfoUpdateDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ApiResult>>> {
            const localVarAxiosArgs = await DoctorAdviceInfoApiAxiosParamCreator(configuration).apiDoctorAdviceInfoUpdatePut(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DoctorAdviceInfoApi - factory interface
 * @export
 */
export const DoctorAdviceInfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDoctorAdviceInfoDeleteIdDelete(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<ApiResult>> {
            return DoctorAdviceInfoApiFp(configuration).apiDoctorAdviceInfoDeleteIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDoctorAdviceInfoGetIdGet(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<DoctorAdviceInfoDtoApiResult>> {
            return DoctorAdviceInfoApiFp(configuration).apiDoctorAdviceInfoGetIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GetPagedListDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDoctorAdviceInfoGetPagedListPost(body?: GetPagedListDto, options?: AxiosRequestConfig): Promise<AxiosResponse<DoctorAdviceInfoDtoPagedListDtoApiResult>> {
            return DoctorAdviceInfoApiFp(configuration).apiDoctorAdviceInfoGetPagedListPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DoctorAdviceInfoCreateDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDoctorAdviceInfoInsertPost(body?: DoctorAdviceInfoCreateDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ApiResult>> {
            return DoctorAdviceInfoApiFp(configuration).apiDoctorAdviceInfoInsertPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {DoctorAdviceInfoUpdateDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDoctorAdviceInfoUpdatePut(body?: DoctorAdviceInfoUpdateDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ApiResult>> {
            return DoctorAdviceInfoApiFp(configuration).apiDoctorAdviceInfoUpdatePut(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DoctorAdviceInfoApi - object-oriented interface
 * @export
 * @class DoctorAdviceInfoApi
 * @extends {BaseAPI}
 */
export class DoctorAdviceInfoApi extends BaseAPI {
    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DoctorAdviceInfoApi
     */
    public async apiDoctorAdviceInfoDeleteIdDelete(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<ApiResult>> {
        return DoctorAdviceInfoApiFp(this.configuration).apiDoctorAdviceInfoDeleteIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DoctorAdviceInfoApi
     */
    public async apiDoctorAdviceInfoGetIdGet(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<DoctorAdviceInfoDtoApiResult>> {
        return DoctorAdviceInfoApiFp(this.configuration).apiDoctorAdviceInfoGetIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {GetPagedListDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DoctorAdviceInfoApi
     */
    public async apiDoctorAdviceInfoGetPagedListPost(body?: GetPagedListDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<DoctorAdviceInfoDtoPagedListDtoApiResult>> {
        return DoctorAdviceInfoApiFp(this.configuration).apiDoctorAdviceInfoGetPagedListPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {DoctorAdviceInfoCreateDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DoctorAdviceInfoApi
     */
    public async apiDoctorAdviceInfoInsertPost(body?: DoctorAdviceInfoCreateDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<ApiResult>> {
        return DoctorAdviceInfoApiFp(this.configuration).apiDoctorAdviceInfoInsertPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {DoctorAdviceInfoUpdateDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DoctorAdviceInfoApi
     */
    public async apiDoctorAdviceInfoUpdatePut(body?: DoctorAdviceInfoUpdateDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<ApiResult>> {
        return DoctorAdviceInfoApiFp(this.configuration).apiDoctorAdviceInfoUpdatePut(body, options).then((request) => request(this.axios, this.basePath));
    }
}
