/* tslint:disable */
/* eslint-disable */
/**
 * MedicalManagement.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ApiResult } from '../models';
import { GetPagedListDto } from '../models';
import { PrescriptionInfoCreateDto } from '../models';
import { PrescriptionInfoDtoApiResult } from '../models';
import { PrescriptionInfoDtoPagedListDtoApiResult } from '../models';
import { PrescriptionInfoUpdateDto } from '../models';
/**
 * PrescriptionInfoApi - axios parameter creator
 * @export
 */
export const PrescriptionInfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrescriptionInfoDeleteIdDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiPrescriptionInfoDeleteIdDelete.');
            }
            const localVarPath = `/api/PrescriptionInfo/Delete/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrescriptionInfoGetIdGet: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiPrescriptionInfoGetIdGet.');
            }
            const localVarPath = `/api/PrescriptionInfo/Get/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {GetPagedListDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrescriptionInfoGetPagedListPost: async (body?: GetPagedListDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/PrescriptionInfo/GetPagedList`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PrescriptionInfoCreateDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrescriptionInfoInsertPost: async (body?: PrescriptionInfoCreateDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/PrescriptionInfo/Insert`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {PrescriptionInfoUpdateDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrescriptionInfoUpdatePut: async (body?: PrescriptionInfoUpdateDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/PrescriptionInfo/Update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PrescriptionInfoApi - functional programming interface
 * @export
 */
export const PrescriptionInfoApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrescriptionInfoDeleteIdDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ApiResult>>> {
            const localVarAxiosArgs = await PrescriptionInfoApiAxiosParamCreator(configuration).apiPrescriptionInfoDeleteIdDelete(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrescriptionInfoGetIdGet(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PrescriptionInfoDtoApiResult>>> {
            const localVarAxiosArgs = await PrescriptionInfoApiAxiosParamCreator(configuration).apiPrescriptionInfoGetIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {GetPagedListDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrescriptionInfoGetPagedListPost(body?: GetPagedListDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PrescriptionInfoDtoPagedListDtoApiResult>>> {
            const localVarAxiosArgs = await PrescriptionInfoApiAxiosParamCreator(configuration).apiPrescriptionInfoGetPagedListPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {PrescriptionInfoCreateDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrescriptionInfoInsertPost(body?: PrescriptionInfoCreateDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ApiResult>>> {
            const localVarAxiosArgs = await PrescriptionInfoApiAxiosParamCreator(configuration).apiPrescriptionInfoInsertPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {PrescriptionInfoUpdateDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrescriptionInfoUpdatePut(body?: PrescriptionInfoUpdateDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ApiResult>>> {
            const localVarAxiosArgs = await PrescriptionInfoApiAxiosParamCreator(configuration).apiPrescriptionInfoUpdatePut(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PrescriptionInfoApi - factory interface
 * @export
 */
export const PrescriptionInfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrescriptionInfoDeleteIdDelete(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<ApiResult>> {
            return PrescriptionInfoApiFp(configuration).apiPrescriptionInfoDeleteIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrescriptionInfoGetIdGet(id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<PrescriptionInfoDtoApiResult>> {
            return PrescriptionInfoApiFp(configuration).apiPrescriptionInfoGetIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {GetPagedListDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrescriptionInfoGetPagedListPost(body?: GetPagedListDto, options?: AxiosRequestConfig): Promise<AxiosResponse<PrescriptionInfoDtoPagedListDtoApiResult>> {
            return PrescriptionInfoApiFp(configuration).apiPrescriptionInfoGetPagedListPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PrescriptionInfoCreateDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrescriptionInfoInsertPost(body?: PrescriptionInfoCreateDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ApiResult>> {
            return PrescriptionInfoApiFp(configuration).apiPrescriptionInfoInsertPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {PrescriptionInfoUpdateDto} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrescriptionInfoUpdatePut(body?: PrescriptionInfoUpdateDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ApiResult>> {
            return PrescriptionInfoApiFp(configuration).apiPrescriptionInfoUpdatePut(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PrescriptionInfoApi - object-oriented interface
 * @export
 * @class PrescriptionInfoApi
 * @extends {BaseAPI}
 */
export class PrescriptionInfoApi extends BaseAPI {
    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrescriptionInfoApi
     */
    public async apiPrescriptionInfoDeleteIdDelete(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<ApiResult>> {
        return PrescriptionInfoApiFp(this.configuration).apiPrescriptionInfoDeleteIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrescriptionInfoApi
     */
    public async apiPrescriptionInfoGetIdGet(id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<PrescriptionInfoDtoApiResult>> {
        return PrescriptionInfoApiFp(this.configuration).apiPrescriptionInfoGetIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {GetPagedListDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrescriptionInfoApi
     */
    public async apiPrescriptionInfoGetPagedListPost(body?: GetPagedListDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<PrescriptionInfoDtoPagedListDtoApiResult>> {
        return PrescriptionInfoApiFp(this.configuration).apiPrescriptionInfoGetPagedListPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {PrescriptionInfoCreateDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrescriptionInfoApi
     */
    public async apiPrescriptionInfoInsertPost(body?: PrescriptionInfoCreateDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<ApiResult>> {
        return PrescriptionInfoApiFp(this.configuration).apiPrescriptionInfoInsertPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {PrescriptionInfoUpdateDto} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrescriptionInfoApi
     */
    public async apiPrescriptionInfoUpdatePut(body?: PrescriptionInfoUpdateDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<ApiResult>> {
        return PrescriptionInfoApiFp(this.configuration).apiPrescriptionInfoUpdatePut(body, options).then((request) => request(this.axios, this.basePath));
    }
}
