/* tslint:disable */
/* eslint-disable */
/**
 * MedicalManagement.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DoctorInfoDto } from './doctor-info-dto';
/**
 * 
 * @export
 * @interface DoctorInfoDtoPagedListDto
 */
export interface DoctorInfoDtoPagedListDto {
    /**
     * 
     * @type {Array<DoctorInfoDto>}
     * @memberof DoctorInfoDtoPagedListDto
     */
    items?: Array<DoctorInfoDto> | null;
    /**
     * 
     * @type {number}
     * @memberof DoctorInfoDtoPagedListDto
     */
    totalCount?: number;
}
