/* tslint:disable */
/* eslint-disable */
/**
 * MedicalManagement.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DoctorAdviceInfoDto } from './doctor-advice-info-dto';
/**
 * 
 * @export
 * @interface DoctorAdviceInfoDtoPagedListDto
 */
export interface DoctorAdviceInfoDtoPagedListDto {
    /**
     * 
     * @type {Array<DoctorAdviceInfoDto>}
     * @memberof DoctorAdviceInfoDtoPagedListDto
     */
    items?: Array<DoctorAdviceInfoDto> | null;
    /**
     * 
     * @type {number}
     * @memberof DoctorAdviceInfoDtoPagedListDto
     */
    totalCount?: number;
}
