/* tslint:disable */
/* eslint-disable */
/**
 * MedicalManagement.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DoctorAdviceInfoCreateDto
 */
export interface DoctorAdviceInfoCreateDto {
    /**
     * 
     * @type {Date}
     * @memberof DoctorAdviceInfoCreateDto
     */
    createDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof DoctorAdviceInfoCreateDto
     */
    doctorInfoId?: number;
    /**
     * 
     * @type {number}
     * @memberof DoctorAdviceInfoCreateDto
     */
    patientInfoId?: number;
    /**
     * 
     * @type {string}
     * @memberof DoctorAdviceInfoCreateDto
     */
    recordContent?: string | null;
}
