/* tslint:disable */
/* eslint-disable */
/**
 * MedicalManagement.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DoctorInfoCreateDto
 */
export interface DoctorInfoCreateDto {
    /**
     * 
     * @type {string}
     * @memberof DoctorInfoCreateDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DoctorInfoCreateDto
     */
    idCard?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DoctorInfoCreateDto
     */
    educationalBackground?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DoctorInfoCreateDto
     */
    professionalTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DoctorInfoCreateDto
     */
    department?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DoctorInfoCreateDto
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DoctorInfoCreateDto
     */
    address?: string | null;
}
