/* tslint:disable */
/* eslint-disable */
/**
 * MedicalManagement.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MedicineInfoDto } from './medicine-info-dto';
/**
 * 
 * @export
 * @interface MedicineInfoDtoPagedListDto
 */
export interface MedicineInfoDtoPagedListDto {
    /**
     * 
     * @type {Array<MedicineInfoDto>}
     * @memberof MedicineInfoDtoPagedListDto
     */
    items?: Array<MedicineInfoDto> | null;
    /**
     * 
     * @type {number}
     * @memberof MedicineInfoDtoPagedListDto
     */
    totalCount?: number;
}
