/* tslint:disable */
/* eslint-disable */
/**
 * MedicalManagement.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MedicineInfoDto
 */
export interface MedicineInfoDto {
    /**
     * 
     * @type {number}
     * @memberof MedicineInfoDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MedicineInfoDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MedicineInfoDto
     */
    catagory?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MedicineInfoDto
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof MedicineInfoDto
     */
    manufacturer?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MedicineInfoDto
     */
    specification?: string | null;
}
