/* tslint:disable */
/* eslint-disable */
/**
 * MedicalManagement.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PatientInfoDto
 */
export interface PatientInfoDto {
    /**
     * 
     * @type {number}
     * @memberof PatientInfoDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatientInfoDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatientInfoDto
     */
    unit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatientInfoDto
     */
    community?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatientInfoDto
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatientInfoDto
     */
    phoneNumber?: string | null;
}
