/* tslint:disable */
/* eslint-disable */
/**
 * MedicalManagement.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PatientInfoDto } from './patient-info-dto';
/**
 * 
 * @export
 * @interface PatientInfoDtoPagedListDto
 */
export interface PatientInfoDtoPagedListDto {
    /**
     * 
     * @type {Array<PatientInfoDto>}
     * @memberof PatientInfoDtoPagedListDto
     */
    items?: Array<PatientInfoDto> | null;
    /**
     * 
     * @type {number}
     * @memberof PatientInfoDtoPagedListDto
     */
    totalCount?: number;
}
