/* tslint:disable */
/* eslint-disable */
/**
 * MedicalManagement.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PrescriptionInfoDto } from './prescription-info-dto';
/**
 * 
 * @export
 * @interface PrescriptionInfoDtoPagedListDto
 */
export interface PrescriptionInfoDtoPagedListDto {
    /**
     * 
     * @type {Array<PrescriptionInfoDto>}
     * @memberof PrescriptionInfoDtoPagedListDto
     */
    items?: Array<PrescriptionInfoDto> | null;
    /**
     * 
     * @type {number}
     * @memberof PrescriptionInfoDtoPagedListDto
     */
    totalCount?: number;
}
