/* tslint:disable */
/* eslint-disable */
/**
 * MedicalManagement.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PrescriptionInfoDto
 */
export interface PrescriptionInfoDto {
    /**
     * 
     * @type {number}
     * @memberof PrescriptionInfoDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PrescriptionInfoDto
     */
    doctorAdviceInfoId?: number;
    /**
     * 
     * @type {number}
     * @memberof PrescriptionInfoDto
     */
    medicineInfoId?: number;
    /**
     * 
     * @type {number}
     * @memberof PrescriptionInfoDto
     */
    number?: number;
}
